// Generated by scripts/build.js. Edit src/ or plugin/entries/, then run npm run build.
(function () {
'use strict';
var modules = {
"plugin/entries/analyzer.js": function(module, exports, require) {
'use strict';

const { createStorage, normalizeConfig } = require("src/storage.js");
const { recordRequest } = require("src/collector.js");

const adapter = {
  read: (key) => $persistentStore.read(key),
  write: (value, key) => $persistentStore.write(value, key)
};

try {
  const storage = createStorage(adapter);
  const state = storage.load();
  state.config = normalizeConfig($argument || {}, state.config);
  const result = recordRequest(state, $request || {});
  if (result.collected || result.reason === 'target-mismatch') storage.save(state);
} catch (error) {
  console.log('[Loon App IP Router] collector error: ' + String(error && error.stack || error));
}

$done({});

},
"src/storage.js": function(module, exports, require) {
'use strict';

const {
  STORAGE_KEY, STATE_VERSION, MAX_HOSTS, MAX_SERIALIZED_BYTES,
  APPS, ANALYZER_MODES, PROXY_MODES
} = require("src/constants.js");

function nowIso(now) {
  return new Date(now == null ? Date.now() : now).toISOString();
}

function createEmptyState(now) {
  return {
    version: STATE_VERSION,
    lifecycle: 'STOPPED',
    config: {
      enabled: true,
      target: 'ALL',
      customTarget: '',
      policy: 'IP',
      mode: 'OBSERVE',
      proxyMode: 'CORE_ONLY',
      customCategories: []
    },
    session: null,
    totalRequests: 0,
    ignoredRequests: 0,
    hosts: {},
    createdAt: nowIso(now),
    updatedAt: nowIso(now)
  };
}

function safeParse(text, now) {
  if (!text) return createEmptyState(now);
  try {
    const value = JSON.parse(text);
    if (!value || value.version !== STATE_VERSION || typeof value.hosts !== 'object') return createEmptyState(now);
    return value;
  } catch (_) {
    const state = createEmptyState(now);
    state.recoveredFromInvalidData = true;
    return state;
  }
}

function byteLength(value) {
  try { return unescape(encodeURIComponent(value)).length; } catch (_) { return value.length; }
}

function hostRetentionScore(record, now) {
  const ageDays = Math.max(0, (now - Date.parse(record.lastSeen || 0)) / 86400000);
  const recognized = record.recognition === 'FINGERPRINT' ? 2 : 0;
  const core = ['API', 'AUTH', 'FEED', 'SEARCH', 'COMMENT', 'USER', 'WEBSOCKET'].includes(record.category) ? 1.5 : 0;
  return Math.log2((record.count || 0) + 1) * 2 + recognized + core + (record.appConfidence || 0) - ageDays / 14;
}

function pruneState(state, options) {
  const now = options && options.now != null ? options.now : Date.now();
  const maxHosts = options && options.maxHosts || MAX_HOSTS;
  const maxBytes = options && options.maxBytes || MAX_SERIALIZED_BYTES;
  let records = Object.entries(state.hosts);
  if (records.length > maxHosts) {
    records.sort((a, b) => hostRetentionScore(b[1], now) - hostRetentionScore(a[1], now));
    state.hosts = Object.fromEntries(records.slice(0, maxHosts));
  }
  let serialized = JSON.stringify(state);
  if (byteLength(serialized) > maxBytes) {
    records = Object.entries(state.hosts).sort((a, b) => hostRetentionScore(a[1], now) - hostRetentionScore(b[1], now));
    while (records.length && byteLength(serialized) > maxBytes) {
      const batch = Math.max(1, Math.ceil(records.length * 0.05));
      for (const [key] of records.splice(0, batch)) delete state.hosts[key];
      serialized = JSON.stringify(state);
    }
  }
  return state;
}

function normalizeConfig(input, current) {
  const source = input || {};
  const target = APPS.includes(String(source.target || '').toUpperCase()) ? String(source.target).toUpperCase() : current.target;
  const mode = ANALYZER_MODES.includes(String(source.mode || '').toUpperCase()) ? String(source.mode).toUpperCase() : current.mode;
  const proxyMode = PROXY_MODES.includes(String(source.proxyMode || source.proxy_mode || '').toUpperCase())
    ? String(source.proxyMode || source.proxy_mode).toUpperCase() : current.proxyMode;
  const customRaw = source.customCategories || source.custom_categories || current.customCategories || [];
  const customCategories = Array.isArray(customRaw)
    ? customRaw.map((v) => String(v).toUpperCase())
    : String(customRaw).split(/[;,\s]+/).filter(Boolean).map((v) => v.toUpperCase());
  return {
    enabled: source.enabled == null ? current.enabled : source.enabled === true || String(source.enabled).toLowerCase() === 'true' || String(source.enabled).toUpperCase() === 'ON',
    target,
    customTarget: String(source.customTarget || source.custom_target || current.customTarget || '').trim().slice(0, 64),
    policy: String(source.policy || current.policy || 'IP').trim().slice(0, 128),
    mode,
    proxyMode,
    customCategories
  };
}

function createStorage(adapter, options) {
  if (!adapter || typeof adapter.read !== 'function' || typeof adapter.write !== 'function') {
    throw new TypeError('storage adapter requires read and write');
  }
  const key = options && options.key || STORAGE_KEY;
  const clock = options && options.clock || (() => Date.now());
  return {
    load() { return safeParse(adapter.read(key), clock()); },
    save(state) {
      state.updatedAt = nowIso(clock());
      pruneState(state, { now: clock(), maxHosts: options && options.maxHosts, maxBytes: options && options.maxBytes });
      return adapter.write(JSON.stringify(state), key);
    },
    clear() { return adapter.write(undefined, key); },
    control(action, config) {
      const state = this.load();
      const command = String(action || '').toUpperCase();
      state.config = normalizeConfig(config, state.config);
      if (command === 'START') {
        state.lifecycle = 'RUNNING';
        state.session = { startedAt: nowIso(clock()), stoppedAt: null, target: state.config.target };
      } else if (command === 'PAUSE') {
        state.lifecycle = 'PAUSED';
      } else if (command === 'STOP') {
        state.lifecycle = 'STOPPED';
        if (state.session) state.session.stoppedAt = nowIso(clock());
      } else if (command === 'CLEAR') {
        this.clear();
        return createEmptyState(clock());
      } else {
        throw new Error('unsupported lifecycle command: ' + command);
      }
      this.save(state);
      return state;
    }
  };
}

module.exports = { createEmptyState, safeParse, pruneState, normalizeConfig, createStorage, byteLength };

},
"src/constants.js": function(module, exports, require) {
'use strict';

const APPS = Object.freeze([
  'ALL',
  'BILIBILI',
  'DOUYIN',
  'NETEASE',
  'WECHAT',
  'WEIBO',
  'XIAOHONGSHU',
  'KUAISHOU',
  'ZHIHU',
  'TIEBA',
  'COOLAPK',
  'CUSTOM'
]);

const CATEGORIES = Object.freeze([
  'API', 'AUTH', 'WEB', 'FEED', 'SEARCH', 'COMMENT', 'USER',
  'STATIC', 'IMAGE', 'VIDEO', 'CDN', 'DOWNLOAD', 'TRACKING',
  'ANALYTICS', 'WEBSOCKET', 'UNKNOWN'
]);

const CORE_CATEGORIES = Object.freeze([
  'API', 'AUTH', 'WEB', 'FEED', 'SEARCH', 'COMMENT', 'USER', 'WEBSOCKET'
]);

const MEDIA_CATEGORIES = Object.freeze([
  'STATIC', 'IMAGE', 'VIDEO', 'CDN', 'DOWNLOAD'
]);

const LOW_VALUE_CATEGORIES = Object.freeze(['TRACKING', 'ANALYTICS']);

const PROXY_MODES = Object.freeze([
  'CORE_ONLY', 'CORE_MEDIA', 'WHOLE_APP', 'CUSTOM'
]);

const ANALYZER_MODES = Object.freeze(['OBSERVE', 'ANALYZE']);
const LIFECYCLE = Object.freeze(['RUNNING', 'PAUSED', 'STOPPED']);

const STORAGE_KEY = 'loon.app.ip.router.state.v1';
const STATE_VERSION = 1;
const MAX_HOSTS = 3000;
const MAX_SERIALIZED_BYTES = 900000;

module.exports = {
  APPS,
  CATEGORIES,
  CORE_CATEGORIES,
  MEDIA_CATEGORIES,
  LOW_VALUE_CATEGORIES,
  PROXY_MODES,
  ANALYZER_MODES,
  LIFECYCLE,
  STORAGE_KEY,
  STATE_VERSION,
  MAX_HOSTS,
  MAX_SERIALIZED_BYTES
};

},
"src/collector.js": function(module, exports, require) {
'use strict';

const { normalizeRequest } = require("src/normalizer.js");
const { detectApp } = require("src/fingerprints.js");
const { classifyRequest } = require("src/classifier.js");

function selectedApp(config, detection) {
  const target = config.target;
  const broadObservation = config.mode === 'ANALYZE' || config.proxyMode === 'WHOLE_APP';
  if (target === 'ALL') {
    if (detection.app !== 'UNKNOWN') return { app: detection.app, recognition: 'FINGERPRINT' };
    return broadObservation ? { app: 'UNKNOWN', recognition: 'UNATTRIBUTED' } : null;
  }
  if (target === 'CUSTOM') {
    return { app: config.customTarget || 'CUSTOM', recognition: 'CUSTOM_SESSION' };
  }
  if (detection.app === target) return { app: target, recognition: 'FINGERPRINT' };
  if (detection.app !== 'UNKNOWN') return null;
  return broadObservation ? { app: target, recognition: 'SESSION' } : null;
}

function recordRequest(state, rawRequest, now) {
  const time = now == null ? Date.now() : now;
  if (!state || state.lifecycle !== 'RUNNING' || !state.config || !state.config.enabled) {
    return { collected: false, reason: 'inactive', state };
  }
  const request = normalizeRequest(rawRequest);
  if (!request) return { collected: false, reason: 'invalid-url', state };
  const detection = detectApp(request.host);
  const attribution = selectedApp(state.config, detection);
  if (!attribution) {
    state.ignoredRequests = (state.ignoredRequests || 0) + 1;
    return { collected: false, reason: 'target-mismatch', state };
  }
  const classification = classifyRequest(request, attribution.app);
  const key = attribution.app + '|' + request.host;
  const seen = new Date(time).toISOString();
  const current = state.hosts[key];
  if (current) {
    current.count += 1;
    current.lastSeen = seen;
    current.categoryCounts[classification.category] = (current.categoryCounts[classification.category] || 0) + 1;
    current.category = Object.keys(current.categoryCounts).sort((a, b) => current.categoryCounts[b] - current.categoryCounts[a])[0];
    current.resourceScore = (current.resourceScore * (current.count - 1) + classification.resourceScore) / current.count;
    current.methods[rawRequest.method || 'UNKNOWN'] = (current.methods[rawRequest.method || 'UNKNOWN'] || 0) + 1;
    if (!current.pathSamples.includes(request.path) && current.pathSamples.length < 5) current.pathSamples.push(request.path);
  } else {
    state.hosts[key] = {
      host: request.host,
      app: attribution.app,
      detectedApp: detection.app,
      appConfidence: detection.strength,
      recognition: attribution.recognition,
      fingerprint: detection.value,
      count: 1,
      firstSeen: seen,
      lastSeen: seen,
      category: classification.category,
      categoryCounts: { [classification.category]: 1 },
      categoryConfidence: classification.confidence,
      resourceScore: classification.resourceScore,
      methods: { [rawRequest.method || 'UNKNOWN']: 1 },
      schemes: { [request.scheme]: 1 },
      pathSamples: [request.path],
      isIP: request.isIP,
      ipVersion: request.ipVersion,
      likelyQuic: /(?:quic|http3|h3)[.-]/i.test(request.host)
    };
  }
  state.totalRequests = (state.totalRequests || 0) + 1;
  return { collected: true, record: state.hosts[key], state };
}

module.exports = { recordRequest, selectedApp };

},
"src/normalizer.js": function(module, exports, require) {
'use strict';

function isIPv4(value) {
  if (!/^\d{1,3}(?:\.\d{1,3}){3}$/.test(value)) return false;
  return value.split('.').every((part) => Number(part) >= 0 && Number(part) <= 255);
}

function isIPv6(value) {
  const text = String(value || '').replace(/^\[|\]$/g, '').toLowerCase();
  if (!text.includes(':') || !/^[0-9a-f:.%]+$/i.test(text)) return false;
  const address = text.split('%')[0];
  if ((address.match(/::/g) || []).length > 1) return false;
  const parts = address.split(':');
  if (!address.includes('::') && parts.length !== 8) return false;
  if (address.includes('::') && parts.length > 8) return false;
  return parts.every((part) => part === '' || /^[0-9a-f]{1,4}$/i.test(part) || isIPv4(part));
}

function normalizeHost(input) {
  if (typeof input !== 'string') return null;
  let raw = input.trim();
  if (!raw) return null;
  raw = raw.replace(/[\u0000-\u001f\u007f]/g, '');
  // Do not depend on the WHATWG URL global: Loon documents $request.url but
  // does not promise a browser URL constructor in every JavaScript runtime.
  raw = raw.replace(/^[a-z][a-z0-9+.-]*:\/\//i, '').replace(/^\/\//, '');
  let authority = raw.split(/[/?#]/)[0];
  authority = authority.slice(authority.lastIndexOf('@') + 1);
  if (!authority) return null;
  let host;
  if (authority.startsWith('[')) {
    const close = authority.indexOf(']');
    if (close < 0) return null;
    host = authority.slice(1, close);
    const remainder = authority.slice(close + 1);
    if (remainder && !/^:\d+$/.test(remainder)) return null;
  } else {
    host = authority;
    const colon = host.lastIndexOf(':');
    if (colon > -1 && host.indexOf(':') === colon && /^\d+$/.test(host.slice(colon + 1))) host = host.slice(0, colon);
  }
  host = host.toLowerCase().replace(/\.+$/, '');
  if (!host || host.length > 253 || /\s/.test(host)) return null;
  if (!isIPv6(host) && !/^[a-z0-9_\-.\u0080-\uffff]+$/i.test(host)) return null;
  return host;
}

function normalizeRequest(input) {
  const url = typeof input === 'string' ? input : input && input.url;
  const host = normalizeHost(url);
  if (!host) return null;
  const raw = String(url || '');
  const schemeMatch = raw.match(/^([a-z][a-z0-9+.-]*):/i);
  let path = '/';
  const withoutScheme = raw.replace(/^[a-z][a-z0-9+.-]*:\/\//i, '').replace(/^\/\//, '');
  const pathIndex = withoutScheme.indexOf('/');
  if (pathIndex >= 0) path = withoutScheme.slice(pathIndex).split(/[?#]/)[0] || '/';
  return {
    host,
    scheme: schemeMatch ? schemeMatch[1].toLowerCase() : 'unknown',
    path: path.toLowerCase(),
    isIP: isIPv4(host) || isIPv6(host),
    ipVersion: isIPv4(host) ? 4 : (isIPv6(host) ? 6 : null)
  };
}

module.exports = { normalizeHost, normalizeRequest, isIPv4, isIPv6 };

},
"src/fingerprints.js": function(module, exports, require) {
'use strict';

// Conservative ownership fingerprints. Broad shared domains (for example
// qq.com and byteimg.com) are intentionally not suffix fingerprints.
const FINGERPRINTS = Object.freeze({
  BILIBILI: {
    suffixes: ['bilibili.com', 'biliapi.net', 'biliapi.com', 'acg.tv', 'biligame.com', 'bilivideo.com'],
    coreSuffixes: ['bilibili.com', 'biliapi.net', 'biliapi.com', 'acg.tv', 'biligame.com'],
    mediaSuffixes: ['bilivideo.com'],
    exact: []
  },
  DOUYIN: {
    suffixes: ['douyin.com', 'douyinvod.com', 'douyinpic.com', 'amemv.com', 'snssdk.com'],
    coreSuffixes: ['douyin.com', 'amemv.com', 'snssdk.com'],
    mediaSuffixes: ['douyinvod.com', 'douyinpic.com'],
    exact: [],
    keywords: ['core-c-lq', 'core-lq', 'normal-c-lq', 'normal-lq', 'search-quic-lq', 'search-lq']
  },
  NETEASE: {
    suffixes: ['music.163.com', 'music.126.net', 'netease.im', '127.net'],
    coreSuffixes: ['music.163.com', 'netease.im'],
    mediaSuffixes: ['music.126.net'],
    exact: [],
    weakSuffixes: ['netease.com']
  },
  WECHAT: {
    suffixes: ['weixin.qq.com'],
    coreSuffixes: ['weixin.qq.com'],
    mediaSuffixes: [],
    exact: ['szshort.weixin.qq.com', 'szextshort.weixin.qq.com', 'szminorshort.weixin.qq.com', 'mp.weixin.qq.com']
  },
  WEIBO: {
    suffixes: ['weibo.com', 'weibo.cn', 'sinaimg.cn'],
    coreSuffixes: ['weibo.com', 'weibo.cn'],
    mediaSuffixes: ['sinaimg.cn'],
    exact: []
  },
  XIAOHONGSHU: {
    suffixes: ['xiaohongshu.com', 'xhscdn.com', 'xiaohongshu.com.cn'],
    coreSuffixes: ['xiaohongshu.com', 'xiaohongshu.com.cn'],
    mediaSuffixes: ['xhscdn.com'],
    exact: []
  },
  KUAISHOU: {
    suffixes: ['kuaishou.com', 'gifshow.com', 'ksapisrv.com'],
    coreSuffixes: ['kuaishou.com', 'gifshow.com', 'ksapisrv.com'],
    mediaSuffixes: [],
    exact: []
  },
  ZHIHU: {
    suffixes: ['zhihu.com', 'zhimg.com'],
    coreSuffixes: ['zhihu.com'],
    mediaSuffixes: ['zhimg.com'],
    exact: []
  },
  TIEBA: {
    suffixes: ['tieba.baidu.com', 'tiebacdn.com'],
    coreSuffixes: ['tieba.baidu.com'],
    mediaSuffixes: ['tiebacdn.com'],
    exact: []
  },
  COOLAPK: {
    suffixes: ['coolapk.com', 'coolapkmarket.com'],
    coreSuffixes: ['coolapk.com', 'coolapkmarket.com'],
    mediaSuffixes: [],
    exact: []
  }
});

function hostMatchesSuffix(host, suffix) {
  return host === suffix || host.endsWith('.' + suffix);
}

function detectApp(host) {
  const matches = [];
  for (const app of Object.keys(FINGERPRINTS)) {
    const fp = FINGERPRINTS[app];
    for (const exact of fp.exact || []) {
      if (host === exact) matches.push({ app, strength: 1, value: exact, kind: 'exact' });
    }
    for (const suffix of fp.suffixes || []) {
      if (hostMatchesSuffix(host, suffix)) {
        matches.push({ app, strength: 0.92 + Math.min(0.07, suffix.length / 1000), value: suffix, kind: 'suffix' });
      }
    }
    for (const suffix of fp.weakSuffixes || []) {
      if (hostMatchesSuffix(host, suffix)) {
        matches.push({ app, strength: 0.58, value: suffix, kind: 'weak-suffix' });
      }
    }
    for (const keyword of fp.keywords || []) {
      if (host.includes(keyword)) matches.push({ app, strength: 0.86, value: keyword, kind: 'keyword' });
    }
  }
  matches.sort((a, b) => b.strength - a.strength || b.value.length - a.value.length);
  return matches[0] || { app: 'UNKNOWN', strength: 0, value: null, kind: 'none' };
}

function fingerprintRole(app, host) {
  const fp = FINGERPRINTS[app];
  if (!fp) return null;
  if ((fp.mediaSuffixes || []).some((suffix) => hostMatchesSuffix(host, suffix))) return 'MEDIA';
  if ((fp.coreSuffixes || []).some((suffix) => hostMatchesSuffix(host, suffix))) return 'CORE';
  return null;
}

function knownSuffixes(app) {
  const fp = FINGERPRINTS[app];
  return fp ? Array.from(new Set([...(fp.coreSuffixes || []), ...(fp.mediaSuffixes || [])])) : [];
}

module.exports = { FINGERPRINTS, hostMatchesSuffix, detectApp, fingerprintRole, knownSuffixes };

},
"src/classifier.js": function(module, exports, require) {
'use strict';

const { fingerprintRole } = require("src/fingerprints.js");

const IMAGE_EXT = /\.(?:avif|bmp|gif|heic|ico|jpe?g|png|svg|webp)(?:$|\?)/i;
const VIDEO_EXT = /\.(?:m3u8|mp4|m4v|mov|ts|webm)(?:$|\?)/i;
const AUDIO_EXT = /\.(?:aac|flac|m4a|mp3|ogg|opus|wav)(?:$|\?)/i;
const STATIC_EXT = /\.(?:css|js|map|ttf|otf|woff2?)(?:$|\?)/i;
const DOWNLOAD_EXT = /\.(?:apk|dmg|exe|ipa|pkg|rar|tar|zip|7z)(?:$|\?)/i;

function classifyRequest(request, app) {
  const host = String(request.host || '').toLowerCase();
  const path = String(request.path || '/').toLowerCase();
  const scheme = String(request.scheme || '').toLowerCase();
  const combined = host + path;
  const reasons = [];
  let category = 'UNKNOWN';
  let confidence = 0.35;
  let resourceScore = 0.25;

  if (scheme === 'ws' || scheme === 'wss' || /(?:^|[.-])(?:ws|websocket)(?:[.-]|$)/.test(host)) {
    category = 'WEBSOCKET'; confidence = 0.9; resourceScore = 0.1; reasons.push('WebSocket scheme or host marker');
  } else if (/(?:analytics|telemetry|metrics|log\.|report\.|beacon)/.test(combined)) {
    category = 'ANALYTICS'; confidence = 0.78; resourceScore = 0.15; reasons.push('analytics marker');
  } else if (/(?:track|tracking|adservice|advert|ads\.)/.test(combined)) {
    category = 'TRACKING'; confidence = 0.76; resourceScore = 0.18; reasons.push('tracking/advertising marker');
  } else if (/(?:login|oauth|passport|sso|token|auth)/.test(combined)) {
    category = 'AUTH'; confidence = 0.86; resourceScore = 0.04; reasons.push('authentication marker');
  } else if (/(?:search|query|suggest)/.test(combined)) {
    category = 'SEARCH'; confidence = 0.82; resourceScore = 0.06; reasons.push('search marker');
  } else if (/(?:comment|reply|danmaku)/.test(combined)) {
    category = 'COMMENT'; confidence = 0.82; resourceScore = 0.06; reasons.push('comment marker');
  } else if (/(?:profile|account|member|user|relation|follow)/.test(combined)) {
    category = 'USER'; confidence = 0.78; resourceScore = 0.06; reasons.push('user marker');
  } else if (/(?:feed|recommend|timeline|aweme)/.test(combined)) {
    category = 'FEED'; confidence = 0.79; resourceScore = 0.08; reasons.push('feed marker');
  } else if (VIDEO_EXT.test(path) || /(?:video|vod|bilivideo|douyinvod|live-play)/.test(host)) {
    category = 'VIDEO'; confidence = 0.91; resourceScore = 0.96; reasons.push('video extension or delivery host');
  } else if (AUDIO_EXT.test(path)) {
    category = 'CDN'; confidence = 0.87; resourceScore = 0.9; reasons.push('audio media extension (mapped to CDN category)');
  } else if (IMAGE_EXT.test(path) || /(?:image|img[.-]|pic[.-]|douyinpic|sinaimg|zhimg|xhscdn)/.test(host)) {
    category = 'IMAGE'; confidence = 0.88; resourceScore = 0.9; reasons.push('image extension or delivery host');
  } else if (DOWNLOAD_EXT.test(path) || /(?:download|dl[.-])/.test(combined)) {
    category = 'DOWNLOAD'; confidence = 0.84; resourceScore = 0.84; reasons.push('download marker');
  } else if (STATIC_EXT.test(path) || /(?:static|assets?)[.-]/.test(host)) {
    category = 'STATIC'; confidence = 0.83; resourceScore = 0.78; reasons.push('static resource marker');
  } else if (/(?:^|[.-])cdn(?:[.-]|$)/.test(host)) {
    // "cdn" is only one signal. Keep the request and lower confidence when
    // the path does not also look like a resource.
    category = 'CDN'; confidence = 0.62; resourceScore = 0.68; reasons.push('CDN host marker without decisive resource type');
  } else if (/(?:^|[.-])api(?:[.-]|$)/.test(host) || /^\/(?:api|v\d|x)\//.test(path)) {
    category = 'API'; confidence = 0.88; resourceScore = 0.03; reasons.push('API host or path marker');
  } else if (/(?:www\.|^m\.|web\.)/.test(host) || /\.(?:html?|php)(?:$|\?)/.test(path)) {
    category = 'WEB'; confidence = 0.69; resourceScore = 0.12; reasons.push('web marker');
  }

  const role = fingerprintRole(app, host);
  if (role === 'MEDIA' && category === 'UNKNOWN') {
    category = 'CDN'; confidence = 0.76; resourceScore = 0.8; reasons.push('known app media suffix');
  } else if (role === 'CORE' && category === 'UNKNOWN') {
    category = 'API'; confidence = 0.7; resourceScore = 0.08; reasons.push('known app core suffix');
  }

  return { category, confidence, resourceScore, reasons };
}

module.exports = { classifyRequest };

}
};
var cache = {};
function require(id) {
  if (cache[id]) return cache[id].exports;
  if (!modules[id]) throw new Error('Module not found: ' + id);
  var module = cache[id] = { exports: {} };
  modules[id](module, module.exports, require);
  return module.exports;
}
require("plugin/entries/analyzer.js");
}());
