// Generated by scripts/build.js. Edit src/ or plugin/entries/, then run npm run build.
(function () {
'use strict';
var modules = {
"plugin/entries/control.js": function(module, exports, require) {
'use strict';

const { createStorage } = require("src/storage.js");

const adapter = {
  read: (key) => $persistentStore.read(key),
  write: (value, key) => $persistentStore.write(value, key)
};

try {
  const storage = createStorage(adapter);
  const args = $argument || {};
  const state = storage.control(args.control || 'START', args);
  const target = state.config.target === 'CUSTOM' ? (state.config.customTarget || 'CUSTOM') : state.config.target;
  $done({
    title: 'Loon App IP Router',
    content: '操作：' + String(args.control || 'START').toUpperCase() + '\n状态：' + state.lifecycle + '\n目标：' + target + '\nHost：' + Object.keys(state.hosts || {}).length
  });
} catch (error) {
  $done({ title: 'Loon App IP Router', content: '操作失败：' + String(error && error.message || error) });
}

},
"src/storage.js": function(module, exports, require) {
'use strict';

const {
  STORAGE_KEY, STATE_VERSION, MAX_HOSTS, MAX_SERIALIZED_BYTES,
  APPS, ANALYZER_MODES, PROXY_MODES
} = require("src/constants.js");

function nowIso(now) {
  return new Date(now == null ? Date.now() : now).toISOString();
}

function createEmptyState(now) {
  return {
    version: STATE_VERSION,
    lifecycle: 'STOPPED',
    config: {
      enabled: true,
      target: 'ALL',
      customTarget: '',
      policy: 'IP',
      mode: 'OBSERVE',
      proxyMode: 'CORE_ONLY',
      customCategories: []
    },
    session: null,
    totalRequests: 0,
    ignoredRequests: 0,
    hosts: {},
    createdAt: nowIso(now),
    updatedAt: nowIso(now)
  };
}

function safeParse(text, now) {
  if (!text) return createEmptyState(now);
  try {
    const value = JSON.parse(text);
    if (!value || value.version !== STATE_VERSION || typeof value.hosts !== 'object') return createEmptyState(now);
    return value;
  } catch (_) {
    const state = createEmptyState(now);
    state.recoveredFromInvalidData = true;
    return state;
  }
}

function byteLength(value) {
  try { return unescape(encodeURIComponent(value)).length; } catch (_) { return value.length; }
}

function hostRetentionScore(record, now) {
  const ageDays = Math.max(0, (now - Date.parse(record.lastSeen || 0)) / 86400000);
  const recognized = record.recognition === 'FINGERPRINT' ? 2 : 0;
  const core = ['API', 'AUTH', 'FEED', 'SEARCH', 'COMMENT', 'USER', 'WEBSOCKET'].includes(record.category) ? 1.5 : 0;
  return Math.log2((record.count || 0) + 1) * 2 + recognized + core + (record.appConfidence || 0) - ageDays / 14;
}

function pruneState(state, options) {
  const now = options && options.now != null ? options.now : Date.now();
  const maxHosts = options && options.maxHosts || MAX_HOSTS;
  const maxBytes = options && options.maxBytes || MAX_SERIALIZED_BYTES;
  let records = Object.entries(state.hosts);
  if (records.length > maxHosts) {
    records.sort((a, b) => hostRetentionScore(b[1], now) - hostRetentionScore(a[1], now));
    state.hosts = Object.fromEntries(records.slice(0, maxHosts));
  }
  let serialized = JSON.stringify(state);
  if (byteLength(serialized) > maxBytes) {
    records = Object.entries(state.hosts).sort((a, b) => hostRetentionScore(a[1], now) - hostRetentionScore(b[1], now));
    while (records.length && byteLength(serialized) > maxBytes) {
      const batch = Math.max(1, Math.ceil(records.length * 0.05));
      for (const [key] of records.splice(0, batch)) delete state.hosts[key];
      serialized = JSON.stringify(state);
    }
  }
  return state;
}

function normalizeConfig(input, current) {
  const source = input || {};
  const target = APPS.includes(String(source.target || '').toUpperCase()) ? String(source.target).toUpperCase() : current.target;
  const mode = ANALYZER_MODES.includes(String(source.mode || '').toUpperCase()) ? String(source.mode).toUpperCase() : current.mode;
  const proxyMode = PROXY_MODES.includes(String(source.proxyMode || source.proxy_mode || '').toUpperCase())
    ? String(source.proxyMode || source.proxy_mode).toUpperCase() : current.proxyMode;
  const customRaw = source.customCategories || source.custom_categories || current.customCategories || [];
  const customCategories = Array.isArray(customRaw)
    ? customRaw.map((v) => String(v).toUpperCase())
    : String(customRaw).split(/[;,\s]+/).filter(Boolean).map((v) => v.toUpperCase());
  return {
    enabled: source.enabled == null ? current.enabled : source.enabled === true || String(source.enabled).toLowerCase() === 'true' || String(source.enabled).toUpperCase() === 'ON',
    target,
    customTarget: String(source.customTarget || source.custom_target || current.customTarget || '').trim().slice(0, 64),
    policy: String(source.policy || current.policy || 'IP').trim().slice(0, 128),
    mode,
    proxyMode,
    customCategories
  };
}

function createStorage(adapter, options) {
  if (!adapter || typeof adapter.read !== 'function' || typeof adapter.write !== 'function') {
    throw new TypeError('storage adapter requires read and write');
  }
  const key = options && options.key || STORAGE_KEY;
  const clock = options && options.clock || (() => Date.now());
  return {
    load() { return safeParse(adapter.read(key), clock()); },
    save(state) {
      state.updatedAt = nowIso(clock());
      pruneState(state, { now: clock(), maxHosts: options && options.maxHosts, maxBytes: options && options.maxBytes });
      return adapter.write(JSON.stringify(state), key);
    },
    clear() { return adapter.write(undefined, key); },
    control(action, config) {
      const state = this.load();
      const command = String(action || '').toUpperCase();
      state.config = normalizeConfig(config, state.config);
      if (command === 'START') {
        state.lifecycle = 'RUNNING';
        state.session = { startedAt: nowIso(clock()), stoppedAt: null, target: state.config.target };
      } else if (command === 'PAUSE') {
        state.lifecycle = 'PAUSED';
      } else if (command === 'STOP') {
        state.lifecycle = 'STOPPED';
        if (state.session) state.session.stoppedAt = nowIso(clock());
      } else if (command === 'CLEAR') {
        this.clear();
        return createEmptyState(clock());
      } else {
        throw new Error('unsupported lifecycle command: ' + command);
      }
      this.save(state);
      return state;
    }
  };
}

module.exports = { createEmptyState, safeParse, pruneState, normalizeConfig, createStorage, byteLength };

},
"src/constants.js": function(module, exports, require) {
'use strict';

const APPS = Object.freeze([
  'ALL',
  'BILIBILI',
  'DOUYIN',
  'NETEASE',
  'WECHAT',
  'WEIBO',
  'XIAOHONGSHU',
  'KUAISHOU',
  'ZHIHU',
  'TIEBA',
  'COOLAPK',
  'CUSTOM'
]);

const CATEGORIES = Object.freeze([
  'API', 'AUTH', 'WEB', 'FEED', 'SEARCH', 'COMMENT', 'USER',
  'STATIC', 'IMAGE', 'VIDEO', 'CDN', 'DOWNLOAD', 'TRACKING',
  'ANALYTICS', 'WEBSOCKET', 'UNKNOWN'
]);

const CORE_CATEGORIES = Object.freeze([
  'API', 'AUTH', 'WEB', 'FEED', 'SEARCH', 'COMMENT', 'USER', 'WEBSOCKET'
]);

const MEDIA_CATEGORIES = Object.freeze([
  'STATIC', 'IMAGE', 'VIDEO', 'CDN', 'DOWNLOAD'
]);

const LOW_VALUE_CATEGORIES = Object.freeze(['TRACKING', 'ANALYTICS']);

const PROXY_MODES = Object.freeze([
  'CORE_ONLY', 'CORE_MEDIA', 'WHOLE_APP', 'CUSTOM'
]);

const ANALYZER_MODES = Object.freeze(['OBSERVE', 'ANALYZE']);
const LIFECYCLE = Object.freeze(['RUNNING', 'PAUSED', 'STOPPED']);

const STORAGE_KEY = 'loon.app.ip.router.state.v1';
const STATE_VERSION = 1;
const MAX_HOSTS = 3000;
const MAX_SERIALIZED_BYTES = 900000;

module.exports = {
  APPS,
  CATEGORIES,
  CORE_CATEGORIES,
  MEDIA_CATEGORIES,
  LOW_VALUE_CATEGORIES,
  PROXY_MODES,
  ANALYZER_MODES,
  LIFECYCLE,
  STORAGE_KEY,
  STATE_VERSION,
  MAX_HOSTS,
  MAX_SERIALIZED_BYTES
};

}
};
var cache = {};
function require(id) {
  if (cache[id]) return cache[id].exports;
  if (!modules[id]) throw new Error('Module not found: ' + id);
  var module = cache[id] = { exports: {} };
  modules[id](module, module.exports, require);
  return module.exports;
}
require("plugin/entries/control.js");
}());
