// Generated by scripts/build.js. Edit src/ or plugin/entries/, then run npm run build.
(function () {
'use strict';
var modules = {
"plugin/entries/export.js": function(module, exports, require) {
'use strict';

const { createStorage, normalizeConfig } = require("src/storage.js");
const { recommendRules, exportConfirmed } = require("src/rules.js");
const { recordsForConfig } = require("src/report.js");

const adapter = {
  read: (key) => $persistentStore.read(key),
  write: (value, key) => $persistentStore.write(value, key)
};

try {
  const state = createStorage(adapter).load();
  state.config = normalizeConfig($argument || {}, state.config);
  const records = recordsForConfig(state);
  const rules = recommendRules(records, {
    policy: state.config.policy,
    proxyMode: state.config.proxyMode,
    customCategories: state.config.customCategories,
    existingRules: ($argument || {}).existing_rules || ''
  });
  const exported = exportConfirmed(rules, ($argument || {}).confirmed_rules || '', {
    existingRules: ($argument || {}).existing_rules || ''
  });
  console.log(exported.text);
  $done({ title: '已确认的 Loon Rule', content: exported.text });
} catch (error) {
  $done({ title: 'Loon App IP Router', content: '导出失败：' + String(error && error.message || error) });
}

},
"src/storage.js": function(module, exports, require) {
'use strict';

const {
  STORAGE_KEY, STATE_VERSION, MAX_HOSTS, MAX_SERIALIZED_BYTES,
  APPS, ANALYZER_MODES, PROXY_MODES
} = require("src/constants.js");

function nowIso(now) {
  return new Date(now == null ? Date.now() : now).toISOString();
}

function createEmptyState(now) {
  return {
    version: STATE_VERSION,
    lifecycle: 'STOPPED',
    config: {
      enabled: true,
      target: 'ALL',
      customTarget: '',
      policy: 'IP',
      mode: 'OBSERVE',
      proxyMode: 'CORE_ONLY',
      customCategories: []
    },
    session: null,
    totalRequests: 0,
    ignoredRequests: 0,
    hosts: {},
    createdAt: nowIso(now),
    updatedAt: nowIso(now)
  };
}

function safeParse(text, now) {
  if (!text) return createEmptyState(now);
  try {
    const value = JSON.parse(text);
    if (!value || value.version !== STATE_VERSION || typeof value.hosts !== 'object') return createEmptyState(now);
    return value;
  } catch (_) {
    const state = createEmptyState(now);
    state.recoveredFromInvalidData = true;
    return state;
  }
}

function byteLength(value) {
  try { return unescape(encodeURIComponent(value)).length; } catch (_) { return value.length; }
}

function hostRetentionScore(record, now) {
  const ageDays = Math.max(0, (now - Date.parse(record.lastSeen || 0)) / 86400000);
  const recognized = record.recognition === 'FINGERPRINT' ? 2 : 0;
  const core = ['API', 'AUTH', 'FEED', 'SEARCH', 'COMMENT', 'USER', 'WEBSOCKET'].includes(record.category) ? 1.5 : 0;
  return Math.log2((record.count || 0) + 1) * 2 + recognized + core + (record.appConfidence || 0) - ageDays / 14;
}

function pruneState(state, options) {
  const now = options && options.now != null ? options.now : Date.now();
  const maxHosts = options && options.maxHosts || MAX_HOSTS;
  const maxBytes = options && options.maxBytes || MAX_SERIALIZED_BYTES;
  let records = Object.entries(state.hosts);
  if (records.length > maxHosts) {
    records.sort((a, b) => hostRetentionScore(b[1], now) - hostRetentionScore(a[1], now));
    state.hosts = Object.fromEntries(records.slice(0, maxHosts));
  }
  let serialized = JSON.stringify(state);
  if (byteLength(serialized) > maxBytes) {
    records = Object.entries(state.hosts).sort((a, b) => hostRetentionScore(a[1], now) - hostRetentionScore(b[1], now));
    while (records.length && byteLength(serialized) > maxBytes) {
      const batch = Math.max(1, Math.ceil(records.length * 0.05));
      for (const [key] of records.splice(0, batch)) delete state.hosts[key];
      serialized = JSON.stringify(state);
    }
  }
  return state;
}

function normalizeConfig(input, current) {
  const source = input || {};
  const target = APPS.includes(String(source.target || '').toUpperCase()) ? String(source.target).toUpperCase() : current.target;
  const mode = ANALYZER_MODES.includes(String(source.mode || '').toUpperCase()) ? String(source.mode).toUpperCase() : current.mode;
  const proxyMode = PROXY_MODES.includes(String(source.proxyMode || source.proxy_mode || '').toUpperCase())
    ? String(source.proxyMode || source.proxy_mode).toUpperCase() : current.proxyMode;
  const customRaw = source.customCategories || source.custom_categories || current.customCategories || [];
  const customCategories = Array.isArray(customRaw)
    ? customRaw.map((v) => String(v).toUpperCase())
    : String(customRaw).split(/[;,\s]+/).filter(Boolean).map((v) => v.toUpperCase());
  return {
    enabled: source.enabled == null ? current.enabled : source.enabled === true || String(source.enabled).toLowerCase() === 'true' || String(source.enabled).toUpperCase() === 'ON',
    target,
    customTarget: String(source.customTarget || source.custom_target || current.customTarget || '').trim().slice(0, 64),
    policy: String(source.policy || current.policy || 'IP').trim().slice(0, 128),
    mode,
    proxyMode,
    customCategories
  };
}

function createStorage(adapter, options) {
  if (!adapter || typeof adapter.read !== 'function' || typeof adapter.write !== 'function') {
    throw new TypeError('storage adapter requires read and write');
  }
  const key = options && options.key || STORAGE_KEY;
  const clock = options && options.clock || (() => Date.now());
  return {
    load() { return safeParse(adapter.read(key), clock()); },
    save(state) {
      state.updatedAt = nowIso(clock());
      pruneState(state, { now: clock(), maxHosts: options && options.maxHosts, maxBytes: options && options.maxBytes });
      return adapter.write(JSON.stringify(state), key);
    },
    clear() { return adapter.write(undefined, key); },
    control(action, config) {
      const state = this.load();
      const command = String(action || '').toUpperCase();
      state.config = normalizeConfig(config, state.config);
      if (command === 'START') {
        state.lifecycle = 'RUNNING';
        state.session = { startedAt: nowIso(clock()), stoppedAt: null, target: state.config.target };
      } else if (command === 'PAUSE') {
        state.lifecycle = 'PAUSED';
      } else if (command === 'STOP') {
        state.lifecycle = 'STOPPED';
        if (state.session) state.session.stoppedAt = nowIso(clock());
      } else if (command === 'CLEAR') {
        this.clear();
        return createEmptyState(clock());
      } else {
        throw new Error('unsupported lifecycle command: ' + command);
      }
      this.save(state);
      return state;
    }
  };
}

module.exports = { createEmptyState, safeParse, pruneState, normalizeConfig, createStorage, byteLength };

},
"src/constants.js": function(module, exports, require) {
'use strict';

const APPS = Object.freeze([
  'ALL',
  'BILIBILI',
  'DOUYIN',
  'NETEASE',
  'WECHAT',
  'WEIBO',
  'XIAOHONGSHU',
  'KUAISHOU',
  'ZHIHU',
  'TIEBA',
  'COOLAPK',
  'CUSTOM'
]);

const CATEGORIES = Object.freeze([
  'API', 'AUTH', 'WEB', 'FEED', 'SEARCH', 'COMMENT', 'USER',
  'STATIC', 'IMAGE', 'VIDEO', 'CDN', 'DOWNLOAD', 'TRACKING',
  'ANALYTICS', 'WEBSOCKET', 'UNKNOWN'
]);

const CORE_CATEGORIES = Object.freeze([
  'API', 'AUTH', 'WEB', 'FEED', 'SEARCH', 'COMMENT', 'USER', 'WEBSOCKET'
]);

const MEDIA_CATEGORIES = Object.freeze([
  'STATIC', 'IMAGE', 'VIDEO', 'CDN', 'DOWNLOAD'
]);

const LOW_VALUE_CATEGORIES = Object.freeze(['TRACKING', 'ANALYTICS']);

const PROXY_MODES = Object.freeze([
  'CORE_ONLY', 'CORE_MEDIA', 'WHOLE_APP', 'CUSTOM'
]);

const ANALYZER_MODES = Object.freeze(['OBSERVE', 'ANALYZE']);
const LIFECYCLE = Object.freeze(['RUNNING', 'PAUSED', 'STOPPED']);

const STORAGE_KEY = 'loon.app.ip.router.state.v1';
const STATE_VERSION = 1;
const MAX_HOSTS = 3000;
const MAX_SERIALIZED_BYTES = 900000;

module.exports = {
  APPS,
  CATEGORIES,
  CORE_CATEGORIES,
  MEDIA_CATEGORIES,
  LOW_VALUE_CATEGORIES,
  PROXY_MODES,
  ANALYZER_MODES,
  LIFECYCLE,
  STORAGE_KEY,
  STATE_VERSION,
  MAX_HOSTS,
  MAX_SERIALIZED_BYTES
};

},
"src/rules.js": function(module, exports, require) {
'use strict';

const { CORE_CATEGORIES, MEDIA_CATEGORIES, LOW_VALUE_CATEGORIES } = require("src/constants.js");
const { knownSuffixes, hostMatchesSuffix } = require("src/fingerprints.js");
const { discoverKeywords } = require("src/keyword.js");
const { clamp, confidenceToStars } = require("src/scoring.js");

const TYPE_ORDER = { DOMAIN: 0, 'DOMAIN-SUFFIX': 1, 'DOMAIN-KEYWORD': 2 };

function normalizePolicy(policy) {
  const value = String(policy || '').trim();
  if (!value || /[,\r\n]/.test(value)) throw new Error('policy must be non-empty and cannot contain comma/newline');
  return value;
}

function categoryAllowed(category, proxyMode, customCategories) {
  if (proxyMode === 'CORE_ONLY') return CORE_CATEGORIES.includes(category);
  if (proxyMode === 'CORE_MEDIA') return CORE_CATEGORIES.includes(category) || MEDIA_CATEGORIES.includes(category);
  if (proxyMode === 'CUSTOM') return (customCategories || []).includes(category);
  return category !== 'UNKNOWN';
}

function buildRule(type, value, policy, confidence, reason, requestCount, hostCount, category, app, eligible) {
  const rating = confidenceToStars(confidence);
  return {
    id: type + ':' + value,
    type,
    value,
    policy,
    confidence: clamp(confidence, 0, 0.99),
    reason,
    requestCount,
    hostCount,
    category,
    app,
    stars: rating.stars,
    rating: rating.glyphs + ' ' + rating.label,
    recommended: Boolean(eligible && confidence >= 0.55),
    eligible: Boolean(eligible),
    coveredBy: null
  };
}

function dominantCategory(records) {
  const counts = {};
  for (const record of records) counts[record.category] = (counts[record.category] || 0) + (record.count || 0);
  return Object.keys(counts).sort((a, b) => counts[b] - counts[a])[0] || 'UNKNOWN';
}

function derivedSuffix(host) {
  const labels = host.split('.').filter(Boolean);
  if (labels.length < 3) return null;
  const commonSecondLevels = new Set(['com.cn', 'net.cn', 'org.cn', 'com.hk', 'co.uk', 'co.jp']);
  const lastTwo = labels.slice(-2).join('.');
  return commonSecondLevels.has(lastTwo) && labels.length >= 3 ? labels.slice(-3).join('.') : lastTwo;
}

function discoverSuffixes(records, app, policy, proxyMode, customCategories) {
  const results = [];
  const observed = records.filter((record) => record.app === app && !record.isIP && ['FINGERPRINT', 'CUSTOM_SESSION'].includes(record.recognition));
  for (const suffix of knownSuffixes(app)) {
    const matching = observed.filter((record) => hostMatchesSuffix(record.host, suffix));
    if (!matching.length) continue;
    const category = dominantCategory(matching);
    const count = matching.reduce((sum, record) => sum + record.count, 0);
    const media = matching.reduce((sum, record) => sum + record.resourceScore * record.count, 0) / Math.max(1, count);
    const confidence = clamp(0.91 + Math.min(0.05, Math.log10(count + 1) * 0.03) - media * 0.28, 0.35, 0.97);
    results.push(buildRule(
      'DOMAIN-SUFFIX', suffix, policy, confidence,
      media > 0.6 ? '已知 App 媒体后缀；资源流量需人工权衡' : '已知 App 归属且覆盖稳定业务 Host',
      count, matching.length, category, app,
      categoryAllowed(category, proxyMode, customCategories)
    ));
  }

  const groups = new Map();
  for (const record of observed) {
    const suffix = derivedSuffix(record.host);
    if (!suffix || suffix.split('.').length < 2) continue;
    if (!groups.has(suffix)) groups.set(suffix, []);
    groups.get(suffix).push(record);
  }
  for (const [suffix, matching] of groups) {
    const distinctHosts = new Set(matching.map((record) => record.host));
    if (distinctHosts.size < 2 || results.some((rule) => rule.value === suffix)) continue;
    const category = dominantCategory(matching);
    const count = matching.reduce((sum, record) => sum + record.count, 0);
    const avgResource = matching.reduce((sum, record) => sum + record.resourceScore * record.count, 0) / Math.max(1, count);
    const customOnly = matching.every((record) => record.recognition === 'CUSTOM_SESSION');
    const confidence = clamp(0.55 + Math.min(0.18, distinctHosts.size * 0.035) + Math.min(0.08, Math.log10(count + 1) * 0.03) - avgResource * 0.18 - (customOnly ? 0.12 : 0), 0.2, 0.85);
    results.push(buildRule(
      'DOMAIN-SUFFIX', suffix, policy, confidence,
      customOnly ? 'CUSTOM 隔离会话中的多个 Host 共享后缀；归属未经内置指纹验证' : '同一 App 的多个已识别 Host 共享稳定可注册域后缀',
      count, distinctHosts.size, category, app,
      categoryAllowed(category, proxyMode, customCategories)
    ));
  }
  return results;
}

function detectConflicts(rules) {
  const suffixes = rules.filter((rule) => rule.type === 'DOMAIN-SUFFIX');
  for (const rule of rules) {
    if (rule.type !== 'DOMAIN') continue;
    const covering = suffixes
      .filter((suffix) => suffix.app === rule.app && hostMatchesSuffix(rule.value, suffix.value))
      .sort((a, b) => b.value.length - a.value.length)[0];
    if (covering) rule.coveredBy = covering.id;
  }
  return rules;
}

function dedupeRules(rules) {
  const map = new Map();
  for (const rule of rules) {
    const key = rule.type + '|' + rule.value.toLowerCase() + '|' + rule.policy;
    const existing = map.get(key);
    if (!existing || rule.confidence > existing.confidence) map.set(key, rule);
  }
  return Array.from(map.values());
}

function parseExistingRules(text) {
  if (Array.isArray(text)) return text;
  const output = [];
  for (const raw of String(text || '').split(/[;\r\n]+/)) {
    const line = raw.trim();
    if (!line || line.startsWith('#') || /^\[Rule\]$/i.test(line)) continue;
    const parts = line.split(',').map((part) => part.trim());
    const type = String(parts[0] || '').toUpperCase();
    if (!['DOMAIN', 'DOMAIN-SUFFIX', 'DOMAIN-KEYWORD'].includes(type) || !parts[1] || !parts[2]) continue;
    output.push({ type, value: parts[1].toLowerCase(), policy: parts.slice(2).join(',').trim(), source: line });
  }
  return output;
}

function existingRuleCovers(candidate, existing) {
  const value = candidate.value.toLowerCase();
  if (existing.type === candidate.type && existing.value === value) return true;
  if (existing.type === 'DOMAIN-SUFFIX' && candidate.type === 'DOMAIN') return hostMatchesSuffix(value, existing.value);
  if (existing.type === 'DOMAIN-SUFFIX' && candidate.type === 'DOMAIN-SUFFIX') return hostMatchesSuffix(value, existing.value);
  if (existing.type === 'DOMAIN-KEYWORD' && candidate.type === 'DOMAIN') return value.includes(existing.value);
  return false;
}

function applyExistingRuleAnalysis(rules, existingText) {
  const existingRules = parseExistingRules(existingText);
  for (const rule of rules) {
    const covering = existingRules.find((existing) => existingRuleCovers(rule, existing));
    if (!covering) continue;
    rule.existingRule = covering.source;
    rule.existingStatus = covering.policy === rule.policy ? 'ALREADY_COVERED' : 'POLICY_SHADOW';
  }
  return rules;
}

function recommendRules(records, options) {
  const policy = normalizePolicy(options && options.policy || 'IP');
  const proxyMode = options && options.proxyMode || 'CORE_ONLY';
  const customCategories = options && options.customCategories || [];
  const apps = Array.from(new Set(records.map((record) => record.app).filter((app) => app && app !== 'UNKNOWN')));
  const rules = [];

  for (const record of records) {
    // Session-attributed and raw-IP hosts are deliberately left in the unknown
    // report. They never become automatic rule candidates.
    if (record.isIP || !['FINGERPRINT', 'CUSTOM_SESSION'].includes(record.recognition)) continue;
    const customSession = record.recognition === 'CUSTOM_SESSION';
    const core = CORE_CATEGORIES.includes(record.category);
    const lowValue = LOW_VALUE_CATEGORIES.includes(record.category);
    let confidence = 0.62 + Math.min(0.14, Math.log10((record.count || 0) + 1) * 0.06) + (record.appConfidence || 0) * 0.2;
    confidence -= (record.resourceScore || 0) * 0.34;
    if (core) confidence += 0.08;
    if (lowValue) confidence -= 0.28;
    if (customSession) confidence -= 0.2;
    confidence = clamp(confidence, 0.1, 0.98);
    rules.push(buildRule(
      'DOMAIN', record.host, policy, confidence,
      customSession
        ? 'CUSTOM 隔离会话归属，未经内置指纹验证，必须人工复核'
        : (record.resourceScore > 0.65 ? '明确 App Host，但资源/CDN 得分较高' : '明确 App Host，适合精确分流'),
      record.count, 1, record.category, record.app,
      categoryAllowed(record.category, proxyMode, customCategories)
    ));
  }

  for (const app of apps) rules.push(...discoverSuffixes(records, app, policy, proxyMode, customCategories));

  for (const candidate of discoverKeywords(records)) {
    if (!apps.includes(candidate.app) || candidate.randomLike) continue;
    rules.push(buildRule(
      'DOMAIN-KEYWORD', candidate.value, policy, candidate.confidence,
      '多个同一 App Host 重复出现稳定片段', candidate.requestCount, candidate.hostCount,
      candidate.category, candidate.app,
      categoryAllowed(candidate.category, proxyMode, customCategories) || candidate.confidence >= 0.85
    ));
  }

  const analyzed = applyExistingRuleAnalysis(detectConflicts(dedupeRules(rules)), options && (options.existingRules || options.existing_rules));
  return analyzed.sort((a, b) =>
    Number(b.recommended) - Number(a.recommended) || b.confidence - a.confidence ||
    TYPE_ORDER[a.type] - TYPE_ORDER[b.type] || a.value.localeCompare(b.value)
  );
}

function parseConfirmations(text) {
  if (Array.isArray(text)) return new Set(text.map((v) => String(v).trim()).filter(Boolean));
  return new Set(String(text || '').split(/[;\r\n]+/).map((v) => v.trim()).filter(Boolean));
}

function exportConfirmed(rules, confirmations, options) {
  const selectedIds = parseConfirmations(confirmations);
  let selected = rules.filter((rule) => selectedIds.has(rule.id));
  const selectedSuffixes = selected.filter((rule) => rule.type === 'DOMAIN-SUFFIX');
  const omitted = [];
  const warnings = [];
  const existingRules = parseExistingRules(options && options.existingRules);
  selected = selected.filter((rule) => {
    const existing = existingRules.find((item) => existingRuleCovers(rule, item));
    if (existing && existing.policy === rule.policy) {
      omitted.push({ rule: rule.id, coveredBy: 'EXISTING:' + existing.source });
      return false;
    }
    if (existing && existing.policy !== rule.policy) {
      warnings.push(rule.id + ' 可能被更早的已有规则遮蔽：' + existing.source);
    }
    if (rule.type !== 'DOMAIN') return true;
    const covering = selectedSuffixes.find((suffix) => suffix.app === rule.app && hostMatchesSuffix(rule.value, suffix.value));
    if (!covering) return true;
    omitted.push({ rule: rule.id, coveredBy: covering.id });
    return false;
  });
  selected = dedupeRules(selected).sort((a, b) =>
    String(a.app).localeCompare(String(b.app)) || TYPE_ORDER[a.type] - TYPE_ORDER[b.type] || a.value.localeCompare(b.value)
  );
  const lines = ['[Rule]', ''];
  let currentApp = null;
  for (const rule of selected) {
    if (rule.app !== currentApp) {
      if (currentApp !== null) lines.push('');
      currentApp = rule.app;
      lines.push('# ===== ' + currentApp + ' =====');
    }
    lines.push(rule.type + ',' + rule.value + ',' + normalizePolicy(rule.policy));
  }
  if (!selected.length) lines.push('# 未导出规则：请先从候选报告复制规则 ID 到“已确认规则”参数。');
  if (options && options.includeWarnings !== false) {
    lines.push('', '# 提示：DOMAIN 置前，其次 DOMAIN-SUFFIX，最后 DOMAIN-KEYWORD。');
    lines.push('# 此导出不能保证覆盖直连 IP、IPv6 绕行或未被 Request Script 观察到的 QUIC/UDP。');
    for (const warning of warnings) lines.push('# 冲突警告：' + warning);
  }
  return { text: lines.join('\n'), selected, omitted, warnings };
}

function matchRule(host, rule) {
  if (rule.type === 'DOMAIN') return host === rule.value;
  if (rule.type === 'DOMAIN-SUFFIX') return hostMatchesSuffix(host, rule.value);
  if (rule.type === 'DOMAIN-KEYWORD') return host.includes(rule.value);
  return false;
}

module.exports = {
  normalizePolicy, categoryAllowed, derivedSuffix, discoverSuffixes, recommendRules,
  detectConflicts, dedupeRules, parseExistingRules, existingRuleCovers, applyExistingRuleAnalysis,
  parseConfirmations, exportConfirmed, matchRule
};

},
"src/fingerprints.js": function(module, exports, require) {
'use strict';

// Conservative ownership fingerprints. Broad shared domains (for example
// qq.com and byteimg.com) are intentionally not suffix fingerprints.
const FINGERPRINTS = Object.freeze({
  BILIBILI: {
    suffixes: ['bilibili.com', 'biliapi.net', 'biliapi.com', 'acg.tv', 'biligame.com', 'bilivideo.com'],
    coreSuffixes: ['bilibili.com', 'biliapi.net', 'biliapi.com', 'acg.tv', 'biligame.com'],
    mediaSuffixes: ['bilivideo.com'],
    exact: []
  },
  DOUYIN: {
    suffixes: ['douyin.com', 'douyinvod.com', 'douyinpic.com', 'amemv.com', 'snssdk.com'],
    coreSuffixes: ['douyin.com', 'amemv.com', 'snssdk.com'],
    mediaSuffixes: ['douyinvod.com', 'douyinpic.com'],
    exact: [],
    keywords: ['core-c-lq', 'core-lq', 'normal-c-lq', 'normal-lq', 'search-quic-lq', 'search-lq']
  },
  NETEASE: {
    suffixes: ['music.163.com', 'music.126.net', 'netease.im', '127.net'],
    coreSuffixes: ['music.163.com', 'netease.im'],
    mediaSuffixes: ['music.126.net'],
    exact: [],
    weakSuffixes: ['netease.com']
  },
  WECHAT: {
    suffixes: ['weixin.qq.com'],
    coreSuffixes: ['weixin.qq.com'],
    mediaSuffixes: [],
    exact: ['szshort.weixin.qq.com', 'szextshort.weixin.qq.com', 'szminorshort.weixin.qq.com', 'mp.weixin.qq.com']
  },
  WEIBO: {
    suffixes: ['weibo.com', 'weibo.cn', 'sinaimg.cn'],
    coreSuffixes: ['weibo.com', 'weibo.cn'],
    mediaSuffixes: ['sinaimg.cn'],
    exact: []
  },
  XIAOHONGSHU: {
    suffixes: ['xiaohongshu.com', 'xhscdn.com', 'xiaohongshu.com.cn'],
    coreSuffixes: ['xiaohongshu.com', 'xiaohongshu.com.cn'],
    mediaSuffixes: ['xhscdn.com'],
    exact: []
  },
  KUAISHOU: {
    suffixes: ['kuaishou.com', 'gifshow.com', 'ksapisrv.com'],
    coreSuffixes: ['kuaishou.com', 'gifshow.com', 'ksapisrv.com'],
    mediaSuffixes: [],
    exact: []
  },
  ZHIHU: {
    suffixes: ['zhihu.com', 'zhimg.com'],
    coreSuffixes: ['zhihu.com'],
    mediaSuffixes: ['zhimg.com'],
    exact: []
  },
  TIEBA: {
    suffixes: ['tieba.baidu.com', 'tiebacdn.com'],
    coreSuffixes: ['tieba.baidu.com'],
    mediaSuffixes: ['tiebacdn.com'],
    exact: []
  },
  COOLAPK: {
    suffixes: ['coolapk.com', 'coolapkmarket.com'],
    coreSuffixes: ['coolapk.com', 'coolapkmarket.com'],
    mediaSuffixes: [],
    exact: []
  }
});

function hostMatchesSuffix(host, suffix) {
  return host === suffix || host.endsWith('.' + suffix);
}

function detectApp(host) {
  const matches = [];
  for (const app of Object.keys(FINGERPRINTS)) {
    const fp = FINGERPRINTS[app];
    for (const exact of fp.exact || []) {
      if (host === exact) matches.push({ app, strength: 1, value: exact, kind: 'exact' });
    }
    for (const suffix of fp.suffixes || []) {
      if (hostMatchesSuffix(host, suffix)) {
        matches.push({ app, strength: 0.92 + Math.min(0.07, suffix.length / 1000), value: suffix, kind: 'suffix' });
      }
    }
    for (const suffix of fp.weakSuffixes || []) {
      if (hostMatchesSuffix(host, suffix)) {
        matches.push({ app, strength: 0.58, value: suffix, kind: 'weak-suffix' });
      }
    }
    for (const keyword of fp.keywords || []) {
      if (host.includes(keyword)) matches.push({ app, strength: 0.86, value: keyword, kind: 'keyword' });
    }
  }
  matches.sort((a, b) => b.strength - a.strength || b.value.length - a.value.length);
  return matches[0] || { app: 'UNKNOWN', strength: 0, value: null, kind: 'none' };
}

function fingerprintRole(app, host) {
  const fp = FINGERPRINTS[app];
  if (!fp) return null;
  if ((fp.mediaSuffixes || []).some((suffix) => hostMatchesSuffix(host, suffix))) return 'MEDIA';
  if ((fp.coreSuffixes || []).some((suffix) => hostMatchesSuffix(host, suffix))) return 'CORE';
  return null;
}

function knownSuffixes(app) {
  const fp = FINGERPRINTS[app];
  return fp ? Array.from(new Set([...(fp.coreSuffixes || []), ...(fp.mediaSuffixes || [])])) : [];
}

module.exports = { FINGERPRINTS, hostMatchesSuffix, detectApp, fingerprintRole, knownSuffixes };

},
"src/keyword.js": function(module, exports, require) {
'use strict';

const { FINGERPRINTS } = require("src/fingerprints.js");

const STOPWORDS = new Set([
  'www', 'api', 'apis', 'app', 'apps', 'com', 'net', 'org', 'cn', 'cdn', 'img', 'image',
  'static', 'video', 'web', 'mobile', 'gateway', 'service', 'server', 'prod', 'client', 'data'
]);

function randomLike(value) {
  const clean = value.replace(/[-_]/g, '');
  if (/^[0-9a-f]{8,}$/i.test(clean)) return true;
  if (/^[0-9a-z]{16,}$/i.test(clean) && !/[aeiou]/i.test(clean)) return true;
  if (/^\d{6,}$/.test(clean)) return true;
  if (/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value)) return true;
  return clean.length >= 8 && (clean.match(/\d/g) || []).length / clean.length > 0.55;
}

function labelCandidates(label) {
  const values = new Set();
  const pieces = label.split(/[-_]+/).filter(Boolean);
  const separator = label.includes('-') ? '-' : '_';
  for (let length = 2; length <= Math.min(5, pieces.length); length += 1) {
    for (let start = 0; start + length <= pieces.length; start += 1) {
      const value = pieces.slice(start, start + length).join(separator);
      if (value.length >= 4 && value.length <= 40) values.add(value);
    }
  }
  if (label.length >= 5 && label.length <= 40 && /[-_]/.test(label)) values.add(label);
  if (label.length >= 8 && label.length <= 40) values.add(label);
  return values;
}

function confidenceForKeyword(value, hostCount, requestCount, dominantRatio, app, category) {
  let score = 0.14;
  score += Math.min(0.28, Math.max(0, hostCount - 1) * 0.1);
  score += Math.min(0.18, Math.log10(requestCount + 1) * 0.075);
  score += Math.min(0.12, value.length / 100);
  if (/[-_]/.test(value)) score += 0.1;
  if (dominantRatio >= 0.9) score += 0.08;
  if (((FINGERPRINTS[app] || {}).keywords || []).includes(value)) score += 0.24;
  if (['API', 'AUTH', 'FEED', 'SEARCH', 'COMMENT', 'USER'].includes(category)) score += 0.06;
  if (randomLike(value)) score -= 0.62;
  if (STOPWORDS.has(value) || value.length < 4) score -= 0.5;
  return Math.max(0, Math.min(0.99, score));
}

function discoverKeywords(records, options) {
  const minHosts = options && options.minHosts || 2;
  const aggregate = new Map();
  for (const record of records) {
    if (!record || !record.host || record.isIP) continue;
    for (const label of record.host.split('.')) {
      for (const value of labelCandidates(label)) {
        if (!aggregate.has(value)) aggregate.set(value, { hosts: new Set(), requestCount: 0, apps: {}, categories: {} });
        const item = aggregate.get(value);
        if (!item.hosts.has(record.host)) item.requestCount += record.count || 0;
        item.hosts.add(record.host);
        item.apps[record.app] = (item.apps[record.app] || 0) + (record.count || 0);
        item.categories[record.category] = (item.categories[record.category] || 0) + (record.count || 0);
      }
    }
  }
  const output = [];
  for (const [value, item] of aggregate) {
    const hostCount = item.hosts.size;
    if (hostCount < minHosts && !Object.values(FINGERPRINTS).some((fp) => (fp.keywords || []).includes(value))) continue;
    const app = Object.keys(item.apps).sort((a, b) => item.apps[b] - item.apps[a])[0];
    const category = Object.keys(item.categories).sort((a, b) => item.categories[b] - item.categories[a])[0];
    const dominantRatio = item.apps[app] / Math.max(1, item.requestCount);
    const confidence = confidenceForKeyword(value, hostCount, item.requestCount, dominantRatio, app, category);
    output.push({
      value, hostCount, requestCount: item.requestCount, app, category, confidence,
      randomLike: randomLike(value),
      hosts: Array.from(item.hosts).sort()
    });
  }
  return output.sort((a, b) => b.confidence - a.confidence || b.requestCount - a.requestCount || b.value.length - a.value.length);
}

module.exports = { discoverKeywords, randomLike, labelCandidates, confidenceForKeyword };

},
"src/scoring.js": function(module, exports, require) {
'use strict';

function clamp(value, min, max) {
  return Math.max(min, Math.min(max, value));
}

function confidenceToStars(confidence) {
  const stars = confidence >= 0.9 ? 5 : confidence >= 0.75 ? 4 : confidence >= 0.55 ? 3 : confidence >= 0.3 ? 2 : 1;
  const labels = ['忽略', '不建议', '可以考虑', '推荐', '强烈推荐'];
  return {
    stars,
    glyphs: '★'.repeat(stars) + '☆'.repeat(5 - stars),
    label: labels[stars - 1],
    percent: Math.round(clamp(confidence, 0, 1) * 100)
  };
}

function weightedAverage(items, valueKey, weightKey) {
  let total = 0;
  let weight = 0;
  for (const item of items) {
    const currentWeight = Number(item[weightKey] || 0);
    total += Number(item[valueKey] || 0) * currentWeight;
    weight += currentWeight;
  }
  return weight ? total / weight : 0;
}

module.exports = { clamp, confidenceToStars, weightedAverage };

},
"src/report.js": function(module, exports, require) {
'use strict';

const { calculateCoverage } = require("src/coverage.js");
const { buildDiagnostics } = require("src/diagnostics.js");
const { confidenceToStars } = require("src/scoring.js");

function durationMinutes(state) {
  if (!state.session || !state.session.startedAt) return 0;
  const end = state.session.stoppedAt || state.updatedAt || new Date().toISOString();
  return Math.max(0, Math.round((Date.parse(end) - Date.parse(state.session.startedAt)) / 60000));
}

function recordsForConfig(state) {
  const records = Object.values(state.hosts || {});
  const config = state.config || {};
  if (!config.target || config.target === 'ALL') return records;
  const app = config.target === 'CUSTOM' ? (config.customTarget || 'CUSTOM') : config.target;
  return records.filter((record) => record.app === app);
}

function generateReport(state, rules) {
  const records = recordsForConfig(state);
  const recommended = rules.filter((rule) => rule.recommended);
  const coverage = calculateCoverage(records, recommended);
  const diagnostics = buildDiagnostics(records);
  const counts = {};
  for (const record of records) counts[record.category] = (counts[record.category] || 0) + 1;
  const lines = [
    '━━━━━━━━━━━━━━━━━━',
    'Loon Rule Analyzer',
    '━━━━━━━━━━━━━━━━━━',
    '',
    '目标：' + (state.config.target === 'CUSTOM' ? (state.config.customTarget || 'CUSTOM') : state.config.target),
    '状态：' + state.lifecycle,
    '分析时间：' + durationMinutes(state) + ' 分钟',
    '请求：' + coverage.totalRequests,
    'Host：' + records.length,
    '核心业务 Host：' + records.filter((r) => ['API', 'AUTH', 'WEB', 'FEED', 'SEARCH', 'COMMENT', 'USER', 'WEBSOCKET'].includes(r.category)).length,
    '媒体 Host：' + records.filter((r) => ['STATIC', 'IMAGE', 'VIDEO', 'CDN', 'DOWNLOAD'].includes(r.category)).length,
    '未知 Host：' + diagnostics.unknown.length,
    '',
    '已识别请求：' + coverage.identifiedPercent + '%',
    '未知请求：' + coverage.unknownPercent + '%',
    '推荐规则覆盖率：' + coverage.ruleCoveragePercent + '%',
    '核心业务覆盖率：' + coverage.core.percent + '%',
    '媒体覆盖率：' + coverage.media.percent + '%',
    '',
    '━━━━━━━━━━━━━━━━━━',
    '规则候选（复制 ID 到“已确认规则”参数后才能导出）',
    '━━━━━━━━━━━━━━━━━━'
  ];
  for (const rule of rules.slice(0, 80)) {
    const rating = confidenceToStars(rule.confidence);
    lines.push(
      '', rating.glyphs + ' ' + rating.percent + '% ' + rating.label,
      rule.type + ',' + rule.value + ',' + rule.policy,
      'ID：' + rule.id,
      'App：' + rule.app + '；分类：' + rule.category + '；Host：' + rule.hostCount + '；请求：' + rule.requestCount,
      '原因：' + rule.reason +
        (rule.coveredBy ? '；已被候选 ' + rule.coveredBy + ' 覆盖' : '') +
        (rule.existingStatus === 'ALREADY_COVERED' ? '；已有同策略规则覆盖：' + rule.existingRule : '') +
        (rule.existingStatus === 'POLICY_SHADOW' ? '；⚠ 可能被不同策略的已有规则遮蔽：' + rule.existingRule : '')
    );
  }
  lines.push('', '━━━━━━━━━━━━━━━━━━', '⚠ 未识别 Host', '━━━━━━━━━━━━━━━━━━');
  for (const record of diagnostics.unknown.slice(0, 100)) {
    lines.push(record.host + ' | 请求 ' + record.count + ' | 首次 ' + record.firstSeen + ' | 最近 ' + record.lastSeen + ' | 建议继续观察');
  }
  if (!diagnostics.unknown.length) lines.push('无');
  lines.push('', '━━━━━━━━━━━━━━━━━━', '诊断提示', '━━━━━━━━━━━━━━━━━━', ...diagnostics.warnings.map((warning) => '⚠ ' + warning));
  return { text: lines.join('\n'), coverage, diagnostics, categoryCounts: counts };
}

module.exports = { generateReport, durationMinutes, recordsForConfig };

},
"src/coverage.js": function(module, exports, require) {
'use strict';

const { CORE_CATEGORIES, MEDIA_CATEGORIES } = require("src/constants.js");
const { matchRule } = require("src/rules.js");

function percent(part, total) {
  return total ? Math.round(part / total * 1000) / 10 : 0;
}

function groupCoverage(records, rules, predicate) {
  const group = records.filter(predicate);
  const requests = group.reduce((sum, record) => sum + (record.count || 0), 0);
  const covered = group.reduce((sum, record) => {
    return sum + (rules.some((rule) => matchRule(record.host, rule)) ? (record.count || 0) : 0);
  }, 0);
  return { requests, coveredRequests: covered, percent: percent(covered, requests) };
}

function calculateCoverage(records, rules) {
  const activeRules = (rules || []).filter((rule) => rule.recommended !== false);
  const total = records.reduce((sum, record) => sum + (record.count || 0), 0);
  const recognizedKinds = ['FINGERPRINT', 'CUSTOM_SESSION'];
  const identified = records.reduce((sum, record) => sum + (recognizedKinds.includes(record.recognition) ? (record.count || 0) : 0), 0);
  const unknownRecords = records.filter((record) => !recognizedKinds.includes(record.recognition) || record.category === 'UNKNOWN');
  const unknown = unknownRecords.reduce((sum, record) => sum + (record.count || 0), 0);
  const all = groupCoverage(records, activeRules, () => true);
  return {
    totalRequests: total,
    identifiedRequests: identified,
    identifiedPercent: percent(identified, total),
    unknownRequests: unknown,
    unknownPercent: percent(unknown, total),
    ruleCoveragePercent: all.percent,
    coveredRequests: all.coveredRequests,
    core: groupCoverage(records, activeRules, (record) => CORE_CATEGORIES.includes(record.category)),
    media: groupCoverage(records, activeRules, (record) => MEDIA_CATEGORIES.includes(record.category)),
    unknown: groupCoverage(records, activeRules, (record) => !recognizedKinds.includes(record.recognition) || record.category === 'UNKNOWN')
  };
}

module.exports = { calculateCoverage, percent, groupCoverage };

},
"src/diagnostics.js": function(module, exports, require) {
'use strict';

function buildDiagnostics(records) {
  const ipv4 = records.filter((record) => record.isIP && record.ipVersion === 4);
  const ipv6 = records.filter((record) => record.isIP && record.ipVersion === 6);
  const websocket = records.filter((record) => record.category === 'WEBSOCKET');
  const likelyQuic = records.filter((record) => record.likelyQuic);
  const unknown = records.filter((record) => !['FINGERPRINT', 'CUSTOM_SESSION'].includes(record.recognition) || record.category === 'UNKNOWN')
    .sort((a, b) => b.count - a.count);
  const warnings = [
    'Request Script 每个请求只会命中最终配置顺序中的首个完整匹配项；更早的脚本可能造成漏采。',
    'HTTP Request Script 不能证明已观察原始 QUIC/UDP；DOMAIN 规则也不等于自动覆盖所有 UDP。'
  ];
  if (ipv4.length) warnings.push('检测到直连 IPv4 字面量 Host；域名规则无法匹配这些目标。');
  if (ipv6.length) warnings.push('检测到 IPv6 字面量 Host，请检查 IPv6 是否绕过代理。');
  else warnings.push('未观察到 IPv6 字面量不代表没有 IPv6 泄漏，请进行双栈出口验证。');
  if (likelyQuic.length) warnings.push('发现疑似 QUIC/HTTP3 Host 标记，需额外核验 UDP 路由。');
  return { ipv4, ipv6, websocket, likelyQuic, unknown, warnings };
}

module.exports = { buildDiagnostics };

}
};
var cache = {};
function require(id) {
  if (cache[id]) return cache[id].exports;
  if (!modules[id]) throw new Error('Module not found: ' + id);
  var module = cache[id] = { exports: {} };
  modules[id](module, module.exports, require);
  return module.exports;
}
require("plugin/entries/export.js");
}());
