'use strict';

const fs = require('node:fs');
const path = require('node:path');

const root = path.resolve(__dirname, '..');
const entryDir = path.join(root, 'plugin', 'entries');
const outDir = path.join(root, 'plugin');
const entries = ['analyzer', 'control', 'report', 'export', 'easy-analyzer', 'easy-report'];

function moduleId(filename) {
  return path.relative(root, filename).replace(/\\/g, '/');
}

function resolveModule(fromFile, request) {
  if (!request.startsWith('.')) throw new Error('Only relative modules can be bundled: ' + request);
  let resolved = path.resolve(path.dirname(fromFile), request);
  if (!path.extname(resolved)) resolved += '.js';
  return resolved;
}

function collect(filename, modules) {
  const absolute = path.resolve(filename);
  const id = moduleId(absolute);
  if (modules.has(id)) return id;
  const source = fs.readFileSync(absolute, 'utf8');
  modules.set(id, '');
  const transformed = source.replace(/require\((['"])(\.\.?\/[^'"]+)\1\)/g, (_all, _quote, request) => {
    const dependency = resolveModule(absolute, request);
    const dependencyId = collect(dependency, modules);
    return 'require(' + JSON.stringify(dependencyId) + ')';
  });
  modules.set(id, transformed);
  return id;
}

function bundle(entryName) {
  const modules = new Map();
  const entryId = collect(path.join(entryDir, entryName + '.js'), modules);
  const factories = Array.from(modules, ([id, source]) =>
    JSON.stringify(id) + ': function(module, exports, require) {\n' + source + '\n}'
  ).join(',\n');
  return [
    '// Generated by scripts/build.js. Edit src/ or plugin/entries/, then run npm run build.',
    '(function () {',
    "'use strict';",
    'var modules = {\n' + factories + '\n};',
    'var cache = {};',
    'function require(id) {',
    '  if (cache[id]) return cache[id].exports;',
    "  if (!modules[id]) throw new Error('Module not found: ' + id);",
    '  var module = cache[id] = { exports: {} };',
    '  modules[id](module, module.exports, require);',
    '  return module.exports;',
    '}',
    'require(' + JSON.stringify(entryId) + ');',
    '}());',
    ''
  ].join('\n');
}

for (const entry of entries) {
  const output = bundle(entry);
  fs.writeFileSync(path.join(outDir, entry + '.js'), output, 'utf8');
  fs.writeFileSync(path.join(root, entry + '.js'), output, 'utf8');
}
fs.copyFileSync(path.join(outDir, 'Loon-App-IP-Router.plugin'), path.join(root, 'Loon-App-IP-Router.plugin'));
fs.copyFileSync(path.join(outDir, 'Loon-App-IP-Router-Easy.plugin'), path.join(root, 'Loon-App-IP-Router-Easy.plugin'));
console.log('Built ' + entries.length + ' Loon scripts in plugin/ and repository root, plus root plugin manifest.');
